name: spring-cloud

networks:
  ecommerce-network:
    name: spring-cloud-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  maria-data:
    name: maria-data
    external: true

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      ecommerce-network:

  config-service:
    build: section 7/config-service
    image: didrkd684/config-service:1.0
    container_name: config-service
    depends_on:
      - rabbitmq
    ports:
      - "8888:8888"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      ecommerce-network:

  eureka-service:
    build: section 1/discoveryservice
    image: didrkd684/eureka-service:1.0
    container_name: eureka-service
    depends_on:
      - config-service
    ports:
      - "8761:8761"
    networks:
      ecommerce-network:

  apigateway-service:
    build: section 2/apigateway-service
    image: didrkd684/apigateway-service:1.0
    container_name: apigateway-service
    depends_on:
      - config-service
      - eureka-service
    ports:
      - "8000:8000"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      ecommerce-network:

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      ecommerce-network:
    volumes:
      - maria-data:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      ecommerce-network:
        ipv4_address: 172.18.0.100

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://172.18.0.101:9092
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      ecommerce-network:
        ipv4_address: 172.18.0.101

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      ecommerce-network:
