server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/study/inflearn/spring-cloud-native-repository
        git:
#          uri: file:///Users/kangdonghee/Desktop/study/inflearn/spring-cloud-git-repository
          uri: https://github.com/chocolaggibbiddori/spring-cloud-config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
