server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/kangdonghee/Desktop/study/inflearn/spring-cloud-git-repository
          uri: https://github.com/chocolaggibbiddori/spring-cloud-config
